server:
  port: 7073

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice
  application:
    name: rating-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
  service-url:
      defaultZone: http://localhost:8761/eureka