
server:
  port: 7072
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: Khushal07
    password: 9423
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: hotel-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka